#' Build the scc argument vector
#'
#' Translates R-level options into the character vector of CLI flags passed
#' to `scc` via [processx::run()].  The output always starts with
#' `c("--format", "json", "--sort", <sort>)`.
#'
#' Flags that only affect `scc`'s tabular display (`--no-hborder`,
#' `--no-size`, `--percent`, COCOMO formatting) are accepted and forwarded but
#' do **not** change the returned tibble, because the wrapper always requests
#' JSON output.
#'
#' @param sort Column to sort by. One of `"name"`, `"files"`, `"lines"`,
#'   `"code"`, `"comments"`, `"blanks"`, `"complexity"`. Default `"code"`.
#' @param by_file Logical. Add `--by-file` flag when `TRUE`.
#'
#' @param no_complexity Logical. Skip complexity calculation (`-c`).
#' @param uloc Logical. Calculate unique lines of code (`-u`).
#' @param dryness Logical. Calculate project DRYness; implies `uloc` (`-a`).
#' @param character Logical. Calculate max/mean characters per line (`-m`).
#' @param percent Logical. Include percentage values in tabular output (`-p`).
#'   No effect on the returned tibble.
#' @param size_unit Character. Set size unit for display. One of `"si"`,
#'   `"binary"`, `"mixed"`, or an `"xkcd-*"` variant.  Default `NULL` (scc
#'   default `"si"`).
#' @param verbose Logical. Verbose output (`-v`).
#' @param debug Logical. Enable debug output.
#'
#' @param no_duplicates Logical. Remove duplicate files from stats (`-d`).
#' @param binary Logical. Disable binary-file detection.
#' @param gen Logical. Identify generated files.
#' @param no_gen Logical. Ignore generated files; implies `gen`.
#' @param min Logical. Identify minified files.
#' @param no_min Logical. Ignore minified files; implies `min`.
#' @param min_gen Logical. Identify minified or generated files (`-z`).
#' @param no_min_gen Logical. Ignore minified or generated files; implies
#'   `min_gen`.
#' @param min_gen_line_length Integer. Bytes per average line threshold for
#'   minified/generated detection. Default `NULL` (scc default `255`).
#' @param generated_markers Character vector. Strings in the head of a file
#'   that mark it as generated. Passed comma-separated. Default `NULL`
#'   (scc defaults: `c("do not edit", "<auto-generated />")`).
#'
#' @param include_ext Character vector. Limit to these file extensions
#'   (comma-separated in one flag, e.g. `c("go", "java")`) (`-i`).
#' @param exclude_ext Character vector. Ignore these file extensions; overrides
#'   `include_ext` (`-x`).
#' @param exclude_dir Character vector. Directories to exclude. Default `NULL`
#'   (scc defaults: `.git`, `.hg`, `.svn`).
#' @param exclude_file Character vector. Ignore files with matching names
#'   (`-n`). Default `NULL` (scc defaults: lock files).
#' @param not_match Character vector. Ignore files/directories whose path
#'   matches any regex pattern. Each element becomes its own `--not-match`
#'   flag (`-M`).
#' @param count_as Character. Map extensions to languages, e.g.
#'   `"jsp:htm,chead:C Header"`.
#' @param remap_all Character. Inspect every file and remap by string match,
#'   e.g. `"-*- C++ -*-:C Header"`.
#' @param remap_unknown Character. Like `remap_all` but only for unknown-type
#'   files.
#' @param include_symlinks Logical. Count symlinked files.
#' @param no_large Logical. Ignore files exceeding `large_byte_count` /
#'   `large_line_count`.
#' @param large_byte_count Integer. Byte threshold for large-file removal.
#'   Default `NULL` (scc default `1000000`).
#' @param large_line_count Integer. Line threshold for large-file removal.
#'   Default `NULL` (scc default `40000`).
#' @param count_ignore Logical. Count `.gitignore` / `.ignore` files.
#'
#' @param no_gitignore Logical. Disable `.gitignore` logic.
#' @param no_gitmodule Logical. Disable `.gitmodules` logic.
#' @param no_ignore Logical. Disable `.ignore` logic.
#' @param no_scc_ignore Logical. Disable `.sccignore` logic.
#'
#' @param no_hborder Logical. Remove horizontal borders from tabular output.
#'   No effect on the returned tibble.
#' @param no_size Logical. Remove size-calculation line from tabular output.
#'   No effect on the returned tibble.
#'
#' @param no_cocomo Logical. Remove COCOMO output from tabular display.
#' @param avg_wage Integer. Average annual wage for COCOMO calculation.
#'   Default `NULL` (scc default `56286`).
#' @param cocomo_project_type Character. COCOMO model type: `"organic"`,
#'   `"semi-detached"`, `"embedded"`, or `"custom,a,b,c,d"`. Default `NULL`
#'   (scc default `"organic"`).
#' @param eaf Numeric. Effort adjustment factor for COCOMO. Default `NULL`
#'   (scc default `1`).
#' @param overhead Numeric. Corporate overhead multiplier for COCOMO. Default
#'   `NULL` (scc default `2.4`).
#' @param currency_symbol Character. Symbol used in COCOMO cost display.
#'   Default `NULL` (scc default `"$"`).
#' @param sloccount_format Logical. Print SLOCCount-style COCOMO output.
#'
#' @param directory_walker_job_workers Integer. Workers for directory walking.
#'   Default `NULL` (scc default `8`).
#' @param file_gc_count Integer. Files parsed before GC is enabled. Default
#'   `NULL` (scc default `10000`).
#' @param file_list_queue_size Integer. Queue size for discovered files.
#'   Default `NULL` (scc default `12`).
#' @param file_process_job_workers Integer. Workers for file-stat collection.
#'   Default `NULL` (scc default `12`).
#' @param file_summary_job_queue_size Integer. Queue size for processed-file
#'   stats. Default `NULL` (scc default `12`).
#'
#' @return Character vector of CLI arguments.
#'
#' @examples
#' \dontrun{
#' build_args("code", by_file = FALSE)
#' build_args("lines", no_complexity = TRUE, include_ext = "r", by_file = TRUE)
#' build_args("code", uloc = TRUE, exclude_dir = c("tests", "vignettes"))
#' }
build_args <- function(
    sort                         = "code",
    by_file                      = FALSE,
    # output
    no_complexity                = FALSE,
    uloc                         = FALSE,
    dryness                      = FALSE,
    character                    = FALSE,
    percent                      = FALSE,
    size_unit                    = NULL,
    verbose                      = FALSE,
    debug                        = FALSE,
    # detection
    no_duplicates                = FALSE,
    binary                       = FALSE,
    gen                          = FALSE,
    no_gen                       = FALSE,
    min                          = FALSE,
    no_min                       = FALSE,
    min_gen                      = FALSE,
    no_min_gen                   = FALSE,
    min_gen_line_length          = NULL,
    generated_markers            = NULL,
    # file / path
    include_ext                  = NULL,
    exclude_ext                  = NULL,
    exclude_dir                  = NULL,
    exclude_file                 = NULL,
    not_match                    = NULL,
    count_as                     = NULL,
    remap_all                    = NULL,
    remap_unknown                = NULL,
    include_symlinks             = FALSE,
    no_large                     = FALSE,
    large_byte_count             = NULL,
    large_line_count             = NULL,
    count_ignore                 = FALSE,
    # git / ignore
    no_gitignore                 = FALSE,
    no_gitmodule                 = FALSE,
    no_ignore                    = FALSE,
    no_scc_ignore                = FALSE,
    # display (tabular only; no effect on returned tibble)
    no_hborder                   = FALSE,
    no_size                      = FALSE,
    # COCOMO
    no_cocomo                    = FALSE,
    avg_wage                     = NULL,
    cocomo_project_type          = NULL,
    eaf                          = NULL,
    overhead                     = NULL,
    currency_symbol              = NULL,
    sloccount_format             = FALSE,
    # performance
    directory_walker_job_workers = NULL,
    file_gc_count                = NULL,
    file_list_queue_size         = NULL,
    file_process_job_workers     = NULL,
    file_summary_job_queue_size  = NULL) {

  sort <- match.arg(
    sort,
    c("name", "files", "lines", "code", "comments", "blanks", "complexity")
  )

  args <- c("--format", "json", "--sort", sort)

  # --- output -----------------------------------------------------------------
  if (isTRUE(by_file))       args <- c(args, "--by-file")
  if (isTRUE(no_complexity)) args <- c(args, "--no-complexity")
  if (isTRUE(uloc))          args <- c(args, "--uloc")
  if (isTRUE(dryness))       args <- c(args, "--dryness")
  if (isTRUE(character))     args <- c(args, "--character")
  if (isTRUE(percent))       args <- c(args, "--percent")
  if (!is.null(size_unit))   args <- c(args, "--size-unit", size_unit)
  if (isTRUE(verbose))       args <- c(args, "--verbose")
  if (isTRUE(debug))         args <- c(args, "--debug")

  # --- detection --------------------------------------------------------------
  if (isTRUE(no_duplicates)) args <- c(args, "--no-duplicates")
  if (isTRUE(binary))        args <- c(args, "--binary")
  if (isTRUE(gen))           args <- c(args, "--gen")
  if (isTRUE(no_gen))        args <- c(args, "--no-gen")
  if (isTRUE(min))           args <- c(args, "--min")
  if (isTRUE(no_min))        args <- c(args, "--no-min")
  if (isTRUE(min_gen))       args <- c(args, "--min-gen")
  if (isTRUE(no_min_gen))    args <- c(args, "--no-min-gen")
  if (!is.null(min_gen_line_length))
    args <- c(args, "--min-gen-line-length", as.character(min_gen_line_length))
  if (!is.null(generated_markers))
    args <- c(args, "--generated-markers", paste(generated_markers, collapse = ","))

  # --- file / path ------------------------------------------------------------
  if (!is.null(include_ext))
    args <- c(args, "--include-ext",  paste(include_ext,  collapse = ","))
  if (!is.null(exclude_ext))
    args <- c(args, "--exclude-ext",  paste(exclude_ext,  collapse = ","))
  if (!is.null(exclude_dir))
    args <- c(args, "--exclude-dir",  paste(exclude_dir,  collapse = ","))
  if (!is.null(exclude_file))
    args <- c(args, "--exclude-file", paste(exclude_file, collapse = ","))
  if (!is.null(not_match)) {
    for (pat in not_match) args <- c(args, "--not-match", pat)
  }
  if (!is.null(count_as))      args <- c(args, "--count-as",      count_as)
  if (!is.null(remap_all))     args <- c(args, "--remap-all",     remap_all)
  if (!is.null(remap_unknown)) args <- c(args, "--remap-unknown", remap_unknown)
  if (isTRUE(include_symlinks)) args <- c(args, "--include-symlinks")
  if (isTRUE(no_large))         args <- c(args, "--no-large")
  if (!is.null(large_byte_count))
    args <- c(args, "--large-byte-count", as.character(large_byte_count))
  if (!is.null(large_line_count))
    args <- c(args, "--large-line-count", as.character(large_line_count))
  if (isTRUE(count_ignore)) args <- c(args, "--count-ignore")

  # --- git / ignore -----------------------------------------------------------
  if (isTRUE(no_gitignore))  args <- c(args, "--no-gitignore")
  if (isTRUE(no_gitmodule))  args <- c(args, "--no-gitmodule")
  if (isTRUE(no_ignore))     args <- c(args, "--no-ignore")
  if (isTRUE(no_scc_ignore)) args <- c(args, "--no-scc-ignore")

  # --- display (tabular only) -------------------------------------------------
  if (isTRUE(no_hborder)) args <- c(args, "--no-hborder")
  if (isTRUE(no_size))    args <- c(args, "--no-size")

  # --- COCOMO -----------------------------------------------------------------
  if (isTRUE(no_cocomo))           args <- c(args, "--no-cocomo")
  if (!is.null(avg_wage))          args <- c(args, "--avg-wage",           as.character(avg_wage))
  if (!is.null(cocomo_project_type))
    args <- c(args, "--cocomo-project-type", cocomo_project_type)
  if (!is.null(eaf))               args <- c(args, "--eaf",                as.character(eaf))
  if (!is.null(overhead))          args <- c(args, "--overhead",           as.character(overhead))
  if (!is.null(currency_symbol))   args <- c(args, "--currency-symbol",    currency_symbol)
  if (isTRUE(sloccount_format))    args <- c(args, "--sloccount-format")

  # --- performance ------------------------------------------------------------
  if (!is.null(directory_walker_job_workers))
    args <- c(args, "--directory-walker-job-workers",
              as.character(directory_walker_job_workers))
  if (!is.null(file_gc_count))
    args <- c(args, "--file-gc-count",         as.character(file_gc_count))
  if (!is.null(file_list_queue_size))
    args <- c(args, "--file-list-queue-size",  as.character(file_list_queue_size))
  if (!is.null(file_process_job_workers))
    args <- c(args, "--file-process-job-workers",
              as.character(file_process_job_workers))
  if (!is.null(file_summary_job_queue_size))
    args <- c(args, "--file-summary-job-queue-size",
              as.character(file_summary_job_queue_size))

  args
}
